# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled5.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.SRAN = QtWidgets.QRadioButton(self.centralwidget)
        self.SRAN.setMaximumSize(QtCore.QSize(60, 40))
        self.SRAN.setChecked(True)
        self.SRAN.setObjectName("SRAN")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.SRAN)
        self.TDD = QtWidgets.QRadioButton(self.centralwidget)
        self.TDD.setMaximumSize(QtCore.QSize(60, 40))
        self.TDD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TDD.setCheckable(True)
        self.TDD.setChecked(False)
        self.TDD.setObjectName("TDD")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.TDD)
        self.verticalLayout_2.addLayout(self.formLayout_10)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_11)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.MRBTS = QtWidgets.QCheckBox(self.tab)
        self.MRBTS.setChecked(True)
        self.MRBTS.setObjectName("MRBTS")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.MRBTS)
        self.IPNO = QtWidgets.QCheckBox(self.tab)
        self.IPNO.setChecked(True)
        self.IPNO.setObjectName("IPNO")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.IPNO)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.RMOD_EQM = QtWidgets.QCheckBox(self.tab_2)
        self.RMOD_EQM.setChecked(True)
        self.RMOD_EQM.setObjectName("RMOD_EQM")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.RMOD_EQM)
        self.SMOD_EQM = QtWidgets.QCheckBox(self.tab_2)
        self.SMOD_EQM.setChecked(True)
        self.SMOD_EQM.setObjectName("SMOD_EQM")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.SMOD_EQM)
        self.BBMOD_EQM = QtWidgets.QCheckBox(self.tab_2)
        self.BBMOD_EQM.setChecked(True)
        self.BBMOD_EQM.setObjectName("BBMOD_EQM")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.BBMOD_EQM)
        self.verticalLayout_5.addLayout(self.formLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.GNSSE_R = QtWidgets.QCheckBox(self.tab_3)
        self.GNSSE_R.setChecked(True)
        self.GNSSE_R.setObjectName("GNSSE_R")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.GNSSE_R)
        self.BBMOD_R = QtWidgets.QCheckBox(self.tab_3)
        self.BBMOD_R.setChecked(True)
        self.BBMOD_R.setObjectName("BBMOD_R")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.BBMOD_R)
        self.SMOD_R = QtWidgets.QCheckBox(self.tab_3)
        self.SMOD_R.setChecked(True)
        self.SMOD_R.setObjectName("SMOD_R")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.SMOD_R)
        self.RMOD_R = QtWidgets.QCheckBox(self.tab_3)
        self.RMOD_R.setChecked(True)
        self.RMOD_R.setObjectName("RMOD_R")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.RMOD_R)
        self.ANTL_R = QtWidgets.QCheckBox(self.tab_3)
        self.ANTL_R.setChecked(True)
        self.ANTL_R.setObjectName("ANTL_R")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ANTL_R)
        self.SFP_R = QtWidgets.QCheckBox(self.tab_3)
        self.SFP_R.setChecked(True)
        self.SFP_R.setObjectName("SFP_R")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.SFP_R)
        self.ASIRMOD_R = QtWidgets.QCheckBox(self.tab_3)
        self.ASIRMOD_R.setChecked(True)
        self.ASIRMOD_R.setObjectName("ASIRMOD_R")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.ASIRMOD_R)
        self.CABLINK_R = QtWidgets.QCheckBox(self.tab_3)
        self.CABLINK_R.setChecked(True)
        self.CABLINK_R.setObjectName("CABLINK_R")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.CABLINK_R)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_6.addLayout(self.gridLayout_9)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.LNBTS = QtWidgets.QCheckBox(self.tab_5)
        self.LNBTS.setChecked(True)
        self.LNBTS.setObjectName("LNBTS")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LNBTS)
        self.LNCEL = QtWidgets.QCheckBox(self.tab_5)
        self.LNCEL.setChecked(True)
        self.LNCEL.setObjectName("LNCEL")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LNCEL)
        self.LNCEL_FDD = QtWidgets.QCheckBox(self.tab_5)
        self.LNCEL_FDD.setChecked(True)
        self.LNCEL_FDD.setObjectName("LNCEL_FDD")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LNCEL_FDD)
        self.NBIOT_FDD = QtWidgets.QCheckBox(self.tab_5)
        self.NBIOT_FDD.setChecked(True)
        self.NBIOT_FDD.setObjectName("NBIOT_FDD")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.NBIOT_FDD)
        self.LNMME = QtWidgets.QCheckBox(self.tab_5)
        self.LNMME.setChecked(True)
        self.LNMME.setObjectName("LNMME")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.LNMME)
        self.LNCEL_TDD = QtWidgets.QCheckBox(self.tab_5)
        self.LNCEL_TDD.setChecked(True)
        self.LNCEL_TDD.setObjectName("LNCEL_TDD")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.LNCEL_TDD)
        self.verticalLayout_7.addLayout(self.formLayout_2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.CHANNEL = QtWidgets.QCheckBox(self.tab_6)
        self.CHANNEL.setChecked(True)
        self.CHANNEL.setObjectName("CHANNEL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CHANNEL)
        self.SECADM = QtWidgets.QCheckBox(self.tab_6)
        self.SECADM.setChecked(True)
        self.SECADM.setObjectName("SECADM")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SECADM)
        self.CHANNELGROUP = QtWidgets.QCheckBox(self.tab_6)
        self.CHANNELGROUP.setChecked(True)
        self.CHANNELGROUP.setObjectName("CHANNELGROUP")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.CHANNELGROUP)
        self.GNSSE_MNL = QtWidgets.QCheckBox(self.tab_6)
        self.GNSSE_MNL.setChecked(True)
        self.GNSSE_MNL.setObjectName("GNSSE_MNL")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.GNSSE_MNL)
        self.FEATCADM = QtWidgets.QCheckBox(self.tab_6)
        self.FEATCADM.setChecked(True)
        self.FEATCADM.setObjectName("FEATCADM")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.FEATCADM)
        self.MPLANENW = QtWidgets.QCheckBox(self.tab_6)
        self.MPLANENW.setChecked(True)
        self.MPLANENW.setObjectName("MPLANENW")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.MPLANENW)
        self.MNL_R = QtWidgets.QCheckBox(self.tab_6)
        self.MNL_R.setChecked(True)
        self.MNL_R.setObjectName("MNL_R")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.MNL_R)
        self.TIME1 = QtWidgets.QCheckBox(self.tab_6)
        self.TIME1.setChecked(True)
        self.TIME1.setObjectName("TIME1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.TIME1)
        self.CLOCK = QtWidgets.QCheckBox(self.tab_6)
        self.CLOCK.setChecked(True)
        self.CLOCK.setObjectName("CLOCK")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.CLOCK)
        self.LCELL = QtWidgets.QCheckBox(self.tab_6)
        self.LCELL.setChecked(True)
        self.LCELL.setObjectName("LCELL")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LCELL)
        self.SYNC = QtWidgets.QCheckBox(self.tab_6)
        self.SYNC.setChecked(True)
        self.SYNC.setObjectName("SYNC")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.SYNC)
        self.verticalLayout_8.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.GNBCF = QtWidgets.QCheckBox(self.tab_7)
        self.GNBCF.setChecked(True)
        self.GNBCF.setObjectName("GNBCF")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.GNBCF)
        self.GNCEL = QtWidgets.QCheckBox(self.tab_7)
        self.GNCEL.setChecked(True)
        self.GNCEL.setObjectName("GNCEL")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.GNCEL)
        self.GNCEL_R = QtWidgets.QCheckBox(self.tab_7)
        self.GNCEL_R.setChecked(True)
        self.GNCEL_R.setObjectName("GNCEL_R")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.GNCEL_R)
        self.CARRIERGROUPC_R = QtWidgets.QCheckBox(self.tab_7)
        self.CARRIERGROUPC_R.setChecked(True)
        self.CARRIERGROUPC_R.setObjectName("CARRIERGROUPC_R")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CARRIERGROUPC_R)
        self.verticalLayout_9.addLayout(self.formLayout_6)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.HW = QtWidgets.QCheckBox(self.tab_8)
        self.HW.setChecked(True)
        self.HW.setObjectName("HW")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.HW)
        self.GNSSE_HW = QtWidgets.QCheckBox(self.tab_8)
        self.GNSSE_HW.setChecked(True)
        self.GNSSE_HW.setObjectName("GNSSE_HW")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.GNSSE_HW)
        self.BBMOD_HW = QtWidgets.QCheckBox(self.tab_8)
        self.BBMOD_HW.setChecked(True)
        self.BBMOD_HW.setObjectName("BBMOD_HW")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.BBMOD_HW)
        self.RMOD_HW = QtWidgets.QCheckBox(self.tab_8)
        self.RMOD_HW.setChecked(True)
        self.RMOD_HW.setObjectName("RMOD_HW")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.RMOD_HW)
        self.SMOD_HW = QtWidgets.QCheckBox(self.tab_8)
        self.SMOD_HW.setChecked(True)
        self.SMOD_HW.setObjectName("SMOD_HW")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.SMOD_HW)
        self.verticalLayout_10.addLayout(self.formLayout_7)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.IPRT = QtWidgets.QCheckBox(self.tab_9)
        self.IPRT.setChecked(True)
        self.IPRT.setObjectName("IPRT")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.IPRT)
        self.IPADDRESSV4 = QtWidgets.QCheckBox(self.tab_9)
        self.IPADDRESSV4.setChecked(True)
        self.IPADDRESSV4.setObjectName("IPADDRESSV4")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.IPADDRESSV4)
        self.VLANIF = QtWidgets.QCheckBox(self.tab_9)
        self.VLANIF.setChecked(True)
        self.VLANIF.setObjectName("VLANIF")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.VLANIF)
        self.IVIF = QtWidgets.QCheckBox(self.tab_9)
        self.IVIF.setChecked(True)
        self.IVIF.setObjectName("IVIF")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.IVIF)
        self.verticalLayout_11.addLayout(self.formLayout_8)
        self.tabWidget.addTab(self.tab_9, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.tabWidget_2.addTab(self.tab_11, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_13)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.UNIT = QtWidgets.QCheckBox(self.tab_13)
        self.UNIT.setChecked(True)
        self.UNIT.setObjectName("UNIT")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.UNIT)
        self.HW_GSM = QtWidgets.QCheckBox(self.tab_13)
        self.HW_GSM.setChecked(True)
        self.HW_GSM.setObjectName("HW_GSM")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.HW_GSM)
        self.horizontalLayout_3.addLayout(self.formLayout_9)
        self.tabWidget_2.addTab(self.tab_13, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.SELECT_ALL = QtWidgets.QCheckBox(self.centralwidget)
        self.SELECT_ALL.setChecked(True)
        self.SELECT_ALL.setObjectName("SELECT_ALL")
        self.verticalLayout_2.addWidget(self.SELECT_ALL)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(120, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 23))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menutest = QtWidgets.QMenu(self.menubar)
        self.menutest.setObjectName("menutest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopenfile = QtWidgets.QAction(MainWindow)
        self.actionopenfile.setObjectName("actionopenfile")
        self.actiontuichu = QtWidgets.QAction(MainWindow)
        self.actiontuichu.setObjectName("actiontuichu")
        self.actiontuic = QtWidgets.QAction(MainWindow)
        self.actiontuic.setObjectName("actiontuic")
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actiontuichu_2 = QtWidgets.QAction(MainWindow)
        self.actiontuichu_2.setObjectName("actiontuichu_2")
        self.actionchu = QtWidgets.QAction(MainWindow)
        self.actionchu.setObjectName("actionchu")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menu.addAction(self.actionopenfile)
        self.menu.addAction(self.actionexit)
        self.menutest.addAction(self.actiontest)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menutest.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.actionopenfile.triggered.connect(MainWindow.btn_click)
        self.actionexit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SRAN Reading Tool "))
        self.SRAN.setText(_translate("MainWindow", "SRAN"))
        self.TDD.setText(_translate("MainWindow", "TDD"))
        self.MRBTS.setText(_translate("MainWindow", "MRBTS"))
        self.IPNO.setText(_translate("MainWindow", "IPNO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "MRBTS"))
        self.RMOD_EQM.setText(_translate("MainWindow", "RMOD"))
        self.SMOD_EQM.setText(_translate("MainWindow", "SMOD"))
        self.BBMOD_EQM.setText(_translate("MainWindow", "BBMOD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "EQM"))
        self.GNSSE_R.setText(_translate("MainWindow", "GNSSE_R"))
        self.BBMOD_R.setText(_translate("MainWindow", "BBMOD_R"))
        self.SMOD_R.setText(_translate("MainWindow", "SMOD_R"))
        self.RMOD_R.setText(_translate("MainWindow", "RMOD_R"))
        self.ANTL_R.setText(_translate("MainWindow", "ANTL_R"))
        self.SFP_R.setText(_translate("MainWindow", "SFP_R"))
        self.ASIRMOD_R.setText(_translate("MainWindow", "ASIRMOD_R"))
        self.CABLINK_R.setText(_translate("MainWindow", "CABLINK_R"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "EQM_R"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "INVUNIT_R"))
        self.LNBTS.setText(_translate("MainWindow", "LNBTS"))
        self.LNCEL.setText(_translate("MainWindow", "LNCEL"))
        self.LNCEL_FDD.setText(_translate("MainWindow", "LNCEL_FDD"))
        self.NBIOT_FDD.setText(_translate("MainWindow", "NBIOT_FDD"))
        self.LNMME.setText(_translate("MainWindow", "LNMME"))
        self.LNCEL_TDD.setText(_translate("MainWindow", "LNCEL_TDD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "LTE BTS"))
        self.CHANNEL.setText(_translate("MainWindow", "CHANNEL"))
        self.SECADM.setText(_translate("MainWindow", "SECADM"))
        self.CHANNELGROUP.setText(_translate("MainWindow", "CHANNELGROUP"))
        self.GNSSE_MNL.setText(_translate("MainWindow", "GNSSE"))
        self.FEATCADM.setText(_translate("MainWindow", "FEATCADM"))
        self.MPLANENW.setText(_translate("MainWindow", "MPLANENW"))
        self.MNL_R.setText(_translate("MainWindow", "MNL_R"))
        self.TIME1.setText(_translate("MainWindow", "TIME"))
        self.CLOCK.setText(_translate("MainWindow", "CLOCK"))
        self.LCELL.setText(_translate("MainWindow", "LCELL"))
        self.SYNC.setText(_translate("MainWindow", "SYNC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "MNL"))
        self.GNBCF.setText(_translate("MainWindow", "GNBCF"))
        self.GNCEL.setText(_translate("MainWindow", "GNCEL"))
        self.GNCEL_R.setText(_translate("MainWindow", "GNCEL_R"))
        self.CARRIERGROUPC_R.setText(_translate("MainWindow", "CARRIERGROUPC_R"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "SRAN GNBTS"))
        self.HW.setText(_translate("MainWindow", "HW"))
        self.GNSSE_HW.setText(_translate("MainWindow", "GNSSE"))
        self.BBMOD_HW.setText(_translate("MainWindow", "BBMOD"))
        self.RMOD_HW.setText(_translate("MainWindow", "RMOD"))
        self.SMOD_HW.setText(_translate("MainWindow", "SMOD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "SRAN HW"))
        self.IPRT.setText(_translate("MainWindow", "IPRT"))
        self.IPADDRESSV4.setText(_translate("MainWindow", "IPADDRESSV4"))
        self.VLANIF.setText(_translate("MainWindow", "VLANIF"))
        self.IVIF.setText(_translate("MainWindow", "IVIF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "TNL"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("MainWindow", "LTE"))
        self.UNIT.setText(_translate("MainWindow", "UNIT"))
        self.HW_GSM.setText(_translate("MainWindow", "HW_GSM"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_13), _translate("MainWindow", "GSM"))
        self.SELECT_ALL.setText(_translate("MainWindow", "SELECT_ALL"))
        self.pushButton_2.setText(_translate("MainWindow", "Delete Datebase"))
        self.pushButton.setText(_translate("MainWindow", "Open XML"))
        self.menu.setTitle(_translate("MainWindow", "Files"))
        self.menutest.setTitle(_translate("MainWindow", "Help"))
        self.actionopenfile.setText(_translate("MainWindow", "Open XML"))
        self.actionopenfile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actiontuichu.setText(_translate("MainWindow", "tuichu"))
        self.actiontuic.setText(_translate("MainWindow", "tuic"))
        self.actiontest.setText(_translate("MainWindow", "About"))
        self.actiontuichu_2.setText(_translate("MainWindow", "tuichu"))
        self.actionchu.setText(_translate("MainWindow", "exit"))
        self.actionexit.setText(_translate("MainWindow", "Quit"))
        self.actionexit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


